import type { Metadata } from "next";
import "./globals.css";

import Header from "../components/header";
import Footer from "../components/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="fa">
      <body className="">
        <div className="relative">
          <Header />
        </div>
        <div className="pt-20">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
